### ISSUE TITLE
MVEL OSGI Compatibility

### ISSUE THREAD

**Issue by n3integration** [mikebrock/mvel#15]
When running MVEL inside of an OSGI container, the following error message has been observed sporadically: 'unable to instantiate accessor compiler'. After looking through the OptimizerFactory class, I noticed that the contextClassLoader is being used to load the optimizer class. In an OSGI framework, this causes indeterministic behavior, since there are several different isolated classloaders.

**Comment by mikebrock** [comment]
fixed

**Comment by grssam** [comment]
Hi, How is this fixed  and what is the fix ?
I am trying to use MVEL in an OSGI framework and I am getting exactly the same issue even using the latest MVEL jars. Basically, it is not able to create an instance of ASM optimizer.
